-- 50 разнообразных задач для тестирования листинга (поиск/фильтры/сортировка/пагинация).
-- created_at намеренно разбросан по времени через интервалы — удобно проверять
-- ?sort=created_at:... и ?created_after=...
-- Применить:
--   docker compose exec -T postgres psql -U tasks_user -d tasks_db < sql/seed.sql

INSERT INTO tasks (title, description, completed, created_at) VALUES
    ('Купить молоко',                 'Взять 2 литра в Пятёрочке',                false, CURRENT_TIMESTAMP - INTERVAL '1 hour'),
    ('Позвонить врачу',               'Записаться на приём к терапевту',          false, CURRENT_TIMESTAMP - INTERVAL '3 hours'),
    ('Code review PR #42',            'Проверить миграции и обработку ошибок',    true,  CURRENT_TIMESTAMP - INTERVAL '6 hours'),
    ('Оплатить интернет',             'Тариф продлевается 5 числа',               false, CURRENT_TIMESTAMP - INTERVAL '12 hours'),
    ('Прочитать главу про SQL',       'JOIN-ы и индексы',                         true,  CURRENT_TIMESTAMP - INTERVAL '1 day'),
    ('Сходить в спортзал',            'День ног',                                 false, CURRENT_TIMESTAMP - INTERVAL '1 day 4 hours'),
    ('Refactor TaskStore',            'Вынести buildTasksWhere',                  false, CURRENT_TIMESTAMP - INTERVAL '2 days'),
    ('Написать тесты на пагинацию',   'limit/offset граничные случаи',            false, CURRENT_TIMESTAMP - INTERVAL '2 days 8 hours'),
    ('Обновить зависимости',          'go get -u, проверить go.sum',              true,  CURRENT_TIMESTAMP - INTERVAL '3 days'),
    ('Забрать посылку',               'Пункт выдачи на Ленина',                   true,  CURRENT_TIMESTAMP - INTERVAL '3 days 5 hours'),
    ('Backup базы',                   'pg_dump перед миграцией',                  false, CURRENT_TIMESTAMP - INTERVAL '4 days'),
    ('Встреча с командой',            'Планирование спринта',                     true,  CURRENT_TIMESTAMP - INTERVAL '4 days 2 hours'),
    ('Полить цветы',                  NULL,                                       false, CURRENT_TIMESTAMP - INTERVAL '5 days'),
    ('Настроить CI',                  'GitHub Actions: build + vet',              false, CURRENT_TIMESTAMP - INTERVAL '5 days 7 hours'),
    ('Купить билеты',                 'Поезд на выходные',                        true,  CURRENT_TIMESTAMP - INTERVAL '6 days'),
    ('Разобрать почту',               'Inbox zero',                               false, CURRENT_TIMESTAMP - INTERVAL '6 days 9 hours'),
    ('Изучить goose',                 'Миграции вместо init.sql',                 false, CURRENT_TIMESTAMP - INTERVAL '7 days'),
    ('Помыть машину',                 NULL,                                       true,  CURRENT_TIMESTAMP - INTERVAL '8 days'),
    ('Добавить healthcheck',          'GET /health и /ready',                     false, CURRENT_TIMESTAMP - INTERVAL '9 days'),
    ('Перейти на slog',               'Структурное логирование',                 false, CURRENT_TIMESTAMP - INTERVAL '10 days'),
    ('Купить подарок',                'День рождения у мамы',                     false, CURRENT_TIMESTAMP - INTERVAL '11 days'),
    ('Договор с подрядчиком',         'Прочитать и подписать',                    true,  CURRENT_TIMESTAMP - INTERVAL '12 days'),
    ('Оптимизировать запрос',         'EXPLAIN ANALYZE на GetAll',                false, CURRENT_TIMESTAMP - INTERVAL '13 days'),
    ('Записаться к стоматологу',      NULL,                                       false, CURRENT_TIMESTAMP - INTERVAL '14 days'),
    ('Прочитать про индексы',         'B-tree vs GIN',                            true,  CURRENT_TIMESTAMP - INTERVAL '15 days'),
    ('Сделать сортировку',            'sort=field:dir + whitelist',               false, CURRENT_TIMESTAMP - INTERVAL '16 days'),
    ('Убрать debug-логи',             'fmt.Println по коду',                      true,  CURRENT_TIMESTAMP - INTERVAL '17 days'),
    ('Купить кофе',                   'Зёрна, обжарка средняя',                   false, CURRENT_TIMESTAMP - INTERVAL '18 days'),
    ('Настроить линтер',              'golangci-lint',                            false, CURRENT_TIMESTAMP - INTERVAL '19 days'),
    ('Созвон с заказчиком',           'Демо новой ручки',                         true,  CURRENT_TIMESTAMP - INTERVAL '20 days'),
    ('Проверить бэкапы',              'Восстановление из дампа',                  false, CURRENT_TIMESTAMP - INTERVAL '21 days'),
    ('Написать README',               'Раздел про запуск',                        false, CURRENT_TIMESTAMP - INTERVAL '22 days'),
    ('Купить продукты',               'Список в заметках',                        true,  CURRENT_TIMESTAMP - INTERVAL '23 days'),
    ('Добавить фильтр completed',     'completed=true|false',                     true,  CURRENT_TIMESTAMP - INTERVAL '24 days'),
    ('Прибраться в гараже',           NULL,                                       false, CURRENT_TIMESTAMP - INTERVAL '25 days'),
    ('Обновить резюме',               'Добавить проект go-rest',                  false, CURRENT_TIMESTAMP - INTERVAL '26 days'),
    ('Изучить context',               'Отмена и таймауты',                        false, CURRENT_TIMESTAMP - INTERVAL '27 days'),
    ('Заменить лампочку',             'На кухне',                                 true,  CURRENT_TIMESTAMP - INTERVAL '28 days'),
    ('Настроить graceful shutdown',   'signal.Notify + Shutdown',                false, CURRENT_TIMESTAMP - INTERVAL '30 days'),
    ('Купить новые наушники',         'Беспроводные',                            false, CURRENT_TIMESTAMP - INTERVAL '32 days'),
    ('Прочитать про pgx',             'Замена lib/pq',                            true,  CURRENT_TIMESTAMP - INTERVAL '34 days'),
    ('Сделать seed-данные',           '50 задач для тестов',                      true,  CURRENT_TIMESTAMP - INTERVAL '36 days'),
    ('Запланировать отпуск',          'Куда-нибудь к морю',                       false, CURRENT_TIMESTAMP - INTERVAL '38 days'),
    ('Проверить SQL-инъекции',        'Whitelist в сортировке',                  false, CURRENT_TIMESTAMP - INTERVAL '40 days'),
    ('Купить книгу по Go',            'The Go Programming Language',              true,  CURRENT_TIMESTAMP - INTERVAL '42 days'),
    ('Настроить docker-compose',      'Healthcheck для postgres',                true,  CURRENT_TIMESTAMP - INTERVAL '45 days'),
    ('Разобраться с volume',          'Почему данные переживают контейнер',      true,  CURRENT_TIMESTAMP - INTERVAL '48 days'),
    ('Добавить связь projects',       'FK tasks.project_id',                      false, CURRENT_TIMESTAMP - INTERVAL '52 days'),
    ('Помыть окна',                   NULL,                                       false, CURRENT_TIMESTAMP - INTERVAL '56 days'),
    ('Финальный обзор кода',          'Пройтись по всему проекту',               false, CURRENT_TIMESTAMP - INTERVAL '60 days');
